### ISSUE TITLE
Input shape 

### ISSUE THREAD

**Issue by hrishikeshps94** [amalF/Kervolution#3]
When I'm trying to give an input shape (None, None, 3). I'm not able to build the model. So is there any way I can build model with above mentioned input shape like in Conv2D layer of keras.

**Comment by amalF** [comment]
Hello, 

are you trying to create your own model ? or are you using the ones that are already implemented ?

**Comment by amalF** [comment]
I'm closing the issue due to lack of activity. Please don't hesitate to reopen it
